# Generated by Django 5.0.2 on 2024-03-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprofile',
            name='interests',
        ),
    ]
