# Generated by Django 5.0.2 on 2024-03-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0002_remove_academicprofile_interests'),
        ('wkeyword', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='interests',
            field=models.ManyToManyField(to='wkeyword.keyword'),
        ),
    ]
