# Generated by Django 5.0.2 on 2024-03-03 03:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Replace('text', models.Value(' '), models.Value(''))), name='text_unique'),
        ),
    ]
